### ISSUE TITLE
Enhance auth error message detail

### ISSUE THREAD

**Issue by bcdady** [Code0x58/gitlab-ci-validate#13]
I'm getting the same authentication-related error message, and it's not helping me troubleshoot / resolve how to use this tool properly. I've tried several different Access Tokens, and several of techniques as shown in the README, but I've not yet gotten this to work, whether local or in a pipeline.

Are there any further details that could be passed through from a failed Gitlab authentication or authorization? For example, if the ACCESS_KEY or the username:password provided do authenticate, but then don't have privileges for the API endpoint, that would be a helpful distinction, from an error message that specified the provided credentials failed to authenticate.

**Comment by Code0x58** [comment]
It seems GitLab only gives `{"message":"401 Unauthorized"}` with the 401 if your credentials are bad. If your token doesn't have permission then you get a 403 instead. The message from the server is now visible in [v0.3.2](https://github.com/Code0x58/gitlab-ci-validate/releases/tag/v0.3.2).
