### ISSUE TITLE
Publish sha hashes of the releases

### ISSUE THREAD

**Issue by drubin** [Code0x58/gitlab-ci-validate#5]
It would be nice if you could publish sha hashes for the releases.

Not sure if gox supports it but I know its standard with goreleaser

**Comment by Code0x58** [comment]
A quick glance doesn't mention gox or [ghr](https://github.com/tcnksm/ghr)  doing that, but looks like both could be replaced with [goreleaser](https://goreleaser.com/). I'd be happy to accept a PR if you've go experience with it

**Comment by Code0x58** [comment]
goreleaser is now used (thanks to their GitHub Action), so as of [v0.3.0](https://github.com/Code0x58/gitlab-ci-validate/releases/tag/v0.3.0) SHAs are included.
