### ISSUE TITLE
GitHub Actions in old format - update needed for CI + release

### ISSUE THREAD

**Issue by Code0x58** [Code0x58/gitlab-ci-validate#9]
This repo uses the old GitHub Action format, so will need converting over to the new YAML based one to provide CI and releases again.

**Comment by bcdady** [comment]
Since updating to GitLab 13.8.4-ee (f65d7b6f349), gitlab-ci-validate is no longer working.
I'm wondering if you think this issue is related, or if I should open a new issue.

Here's what I'm getting:
```zsh
 - Non-200 status from GitLab: 401
```

**Comment by Code0x58** [comment]
> Since updating to GitLab 13.8.4-ee (f65d7b6f349), gitlab-ci-validate is no longer working.
> I'm wondering if you think this issue is related, or if I should open a new issue.
> 
> Here's what I'm getting:
> 
> ```shell
>  - Non-200 status from GitLab: 401
> ```

That'd be a separate issue which I think is covered by this PR: https://github.com/Code0x58/gitlab-ci-validate/pull/8 - would you mind testing that change, and maybe opening an issue to link to that for others to find (when their old version breaks) with the symptoms you're seeing?

_**edit:** I made #11 for the issue and fixed it in v0.3.0_

**Comment by Code0x58** [comment]
Fixed by #10
